#ifndef CONSTS_H_
#define CONSTS_H_

/* Optimisation constants */
enum {
    CLAW_OPT_SPEED,
    CLAW_OPT_MEMORY
};

enum {
    CLAW_ERR_NONE,
    CLAW_ERR_UNKNOWN,
    CLAW_ERR_STACKUNDERFLOW,
    CLAW_ERR_STACKOVERFLOW,
    CLAW_ERR_OUTOFBOUNDS,
    CLAW_ERR_ARGCOUNT,
    CLAW_ERR_DIVBYZERO
};

#endif